Improve autoscrolling
ThibaultJanBeyer/DragSelect pull request #59
Opened 2020-10-30 15:01 UTC by slinhart

Improve autoscrolling by not relying on mouse movement to trigger scrolling.

Currently, autoscrolling only continues so long as the mouse continues moving. This update creates a smoother autoscrolling experience by adding and removing an interval that performs the scrolling as the cursor moves to and away from the edge.

Before
![dragselect-autoscroll-before](https://user-images.githubusercontent.com/8146903/97720899-310d2780-1a9f-11eb-99e6-359876903e48.gif)

After
![dragselect-autoscroll-after](https://user-images.githubusercontent.com/8146903/97720929-38cccc00-1a9f-11eb-98b5-fdc109a8f539.gif)

2020-10-30 15:05 UTC, slinhart commented on src/DragSelect.js
> +    onElementUnselect = function () {},
Above are just formatting changes, they seemed to be inline with the prettierrc defined so I figured this was a welcomed change, but let me know if you'd like me to change this back 👍

2020-11-02 18:49 UTC, ThibaultJanBeyer requested changes
Hi Slinhart! 👋 

Thanks a lot for your contribution, this is seems to be a very nice addition 💪 
I did not check it for functionality yet, added some comments regarding the code, please address them. Make sure you did proper manual testing additionally to the automated tests.

Looking forward to this :)

2020-11-02 18:49 UTC, ThibaultJanBeyer commented on src/DragSelect.js
> +        this._updatePos(this.selector, this._getPosition(event));
Is it nescessary to `_updatePos` and `checkIfInsideSelection` ?
Seems unnescessary? Wouldn't just calling `_autoScroll` be sufficient?

2020-11-02 18:49 UTC, ThibaultJanBeyer commented on src/DragSelect.js
> +  _autoScroll(edge) {
Please add JSDocs

2020-11-02 18:49 UTC, ThibaultJanBeyer commented on src/DragSelect.js
>     * @param {Object} event – event object.
Please update JSDocs: I guess the description in 690 does not match anymore

2020-11-02 18:49 UTC, ThibaultJanBeyer commented on src/DragSelect.js
> +    this.autoScrollInterval = null;
Since this is a private method. Set it to the other ones on class initialization (line 65) and add an underscore `_` to the name and JSDocs :)

2020-11-03 15:14 UTC, slinhart commented on src/DragSelect.js
> +        this._updatePos(this.selector, this._getPosition(event));
`_updatePos` is needed to update the selection box while the autoscrolling happens

`checkIfInsideSelection` is needed to select items while autoscrolling happens.
I can make some gifs of what I mean if this isn't clear 👍

2020-11-03 15:19 UTC, slinhart commented
Hey @ThibaultJanBeyer really great work with this package 🔥 
And thank you for the review. I've made some updates and everything seems to be working properly in the manual testing I've done.

2020-11-04 14:08 UTC, ThibaultJanBeyer commented
> Hey @ThibaultJanBeyer really great work with this package 🔥
> And thank you for the review. I've made some updates and everything seems to be working properly in the manual testing I've done.

Thank you! I'm currently working on some changes and cleaning it up a bit to make it even easier to work with :)

The code looks good. I'll check your changes manually myself as well asap and then merge if everything works.

2020-11-04 14:46 UTC, ThibaultJanBeyer commented
Let me also fix the merge conflicts, no worries :)

2020-11-04 16:39 UTC, merged

2020-11-04 16:45 UTC, ThibaultJanBeyer commented
Merged and deployed! Thank a lot @slinhart 🎉

2020-11-04 18:54 UTC, owenfar commented
@ThibaultJanBeyer I'm happy regarding the smoother scroll experience, it is more aligned with how it works in an OS. The only problem I'm having now with this update is that it keeps scrolling past the actual height. You can actually see this happening on the 'after' example listed above from @slinhart. Is it just me or should it just stop scroll once it detects that the bottom of the area has reached? It feels like a bug to me

2020-11-04 19:01 UTC, owenfar commented
Is there a way to use isCursorNearEdge to disable further scroll perhaps? I'll need to check this later.

2020-11-04 19:40 UTC, slinhart commented
Hey @owenfar could you elaborate on what you mean by "it keeps scrolling past the actual height"? I'm not seeing anything scrolling too far 🤔

2020-11-04 20:45 UTC, owenfar commented
Here you can see what I experience from my side. The scroll should not continue going

![ezgif com-gif-maker](https://user-images.githubusercontent.com/25148235/98165917-f6fcb500-1ee6-11eb-8dfa-a93d392001f9.gif)

2020-11-05 21:28 UTC, ThibaultJanBeyer commented
> @ThibaultJanBeyer I'm happy regarding the smoother scroll experience, it is more aligned with how it works in an OS. The only problem I'm having now with this update is that it keeps scrolling past the actual height. You can actually see this happening on the 'after' example listed above from @slinhart. Is it just me or should it just stop scroll once it detects that the bottom of the area has reached? It feels like a bug to me

Hi @owenfar 👋 thanks a lot for using the library and sharing the use-case.
That is actually the exact same behavior as before. So not a regression nor a "new" bug. It probably just has become more prominent now as it is also scrolling when the mouse is not moving now. Hmm, it's a tricky one, not sure from the top of my head if easily solvable 🤔. Probably as you suggested, adding a stop when it reaches the maximum scroll of the area.
Maybe open an issue regarding this and we can look into it?

Thank you 🍄

2020-11-07 13:18 UTC, owenfar commented
Hello @ThibaultJanBeyer , thank you for the quick reply. Yes, I'll open it as an issue :) I tried having a look but I'm not sure where to start from as I'm not familiar with the code and don't have much time to help unfortunately.